part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const SPLASH = _Paths.SPLASH;
  static const INTRO = _Paths.INTRO;
  static const LOGIN = _Paths.LOGIN;
  static const WELCOME = _Paths.WELCOME;
  static const SIGNUP = _Paths.SIGNUP;
  static const PENDING = _Paths.PENDING;
  static const PROFILE = _Paths.PROFILE;
  static const CHANGEPASSWORD = _Paths.CHANGEPASSWORD;
  static const SUPPORT = _Paths.SUPPORT;
  static const NOTIFICATION = _Paths.NOTIFICATION;
  static const SUGGESTIONS = _Paths.SUGGESTIONS;
  static const SELECTCLASS = _Paths.SELECTCLASS;
  static const ASSIGNMENTS = _Paths.ASSIGNMENTS;
  static const SYLLABUS = _Paths.SYLLABUS;
  static const EXAMLIST = _Paths.EXAMLIST;
  static const SUBJECT = _Paths.SUBJECT;
  static const CHAPTER = _Paths.CHAPTER;
  static const FILES = _Paths.FILES;
  static const TIMETABLE = _Paths.TIMETABLE;
  static const ATTENDENCE = _Paths.ATTENDENCE;
  static const LIVECLASS = _Paths.LIVECLASS;
  static const FEEDETAILS = _Paths.FEEDETAILS;
  static const EVENTS = _Paths.EVENTS;
  static const ASK_DOUBT = _Paths.ASK_DOUBT;
  static const CHAT = _Paths.CHAT;
  static const CHAT_LIST = _Paths.CHAT_LIST;
  static const ADMIN_HOME = _Paths.ADMIN_HOME;
  static const ADMIN_PROFILE = _Paths.ADMIN_PROFILE;
  static const ADMIN_SUPPORT = _Paths.ADMIN_SUPPORT;
  static const ADMIN_ATTENDENCE_OPTION = _Paths.ADMIN_ATTENDENCE_OPTION;
  static const ADMIN_ATTENDENCE_SELECT = _Paths.ADMIN_ATTENDENCE_SELECT;
  static const ADMIN_ATTENDENCE_MARK = _Paths.ADMIN_ATTENDENCE_MARK;
  static const ADMIN_RESULT_TERM = _Paths.ADMIN_RESULT_TERM;
  static const ADMIN_RESULT_CLASS = _Paths.ADMIN_RESULT_CLASS;
  static const ADMIN_MARK_RESULT = _Paths.ADMIN_MARK_RESULT;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const SPLASH = '/splash';
  static const INTRO = '/intro';
  static const LOGIN = '/login';
  static const WELCOME = '/welcome';
  static const SIGNUP = '/signup';
  static const PENDING = '/pending';
  static const PROFILE = '/profile';
  static const CHANGEPASSWORD = '/changePassword';
  static const NOTIFICATION = '/notification';
  static const SUPPORT = '/support';
  static const SUGGESTIONS = '/suggestions';
  static const SELECTCLASS = '/select_class';
  static const ASSIGNMENTS = '/assignments';
  static const SYLLABUS = '/syllabus';
  static const EXAMLIST = '/exam_list';
  static const SUBJECT = '/subject';
  static const CHAPTER = '/chapter';
  static const LIVECLASS = '/live_class';
  static const FILES = '/files';
  static const TIMETABLE = '/timetable';
  static const ATTENDENCE = '/attendence';
  static const FEEDETAILS = '/fee_details';
  static const EVENTS = '/events';
  static const ASK_DOUBT = '/ask_doubt';
  static const CHAT_LIST = '/chat_list';
  static const CHAT = '/chat';
  static const ADMIN_HOME = '/admin-home';
  static const ADMIN_PROFILE = '/admin-profile';
  static const ADMIN_SUPPORT = '/admin-support';
  static const ADMIN_ATTENDENCE_OPTION = '/admin-attendence-option';
  static const ADMIN_ATTENDENCE_SELECT = '/admin-attendence-select';
  static const ADMIN_ATTENDENCE_MARK = '/admin-attendence-mark';
  static const ADMIN_RESULT_TERM = '/admin-result-term';
  static const ADMIN_RESULT_CLASS = '/admin-result-class';
  static const ADMIN_MARK_RESULT = '/admin-mark-result';
}
